name: Auto Daily Commit
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  make-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "Daily update $(date)" >> record.txt
      - run: |
          git config --global user.name "autobot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "daily active update"
          git push
